### ISSUE TITLE
Criar a migração para os outros campos

### ISSUE THREAD

**Issue by barbier** [MinisterioPublicoRJ/cadastro-de-contratos#1]

**Comment by nighto** [comment]
Done on dc9e1cc0c3c93141ca1b134227624c0c2e8f1866.

**Comment by nighto** [comment]
Some notes regarding `_form.html.erb`:

1) check how to enter boolean field
2) dates are stored in `yyyy-mm-dd` format, use a date picker and return date with this format
3) decimal values (`valor_total`) is stored in `XXXXXX.XX` format, use a JS wrapper and return value with this format.
