### ISSUE TITLE
Page with full width

### ISSUE THREAD

**Issue by rlage** [MinisterioPublicoRJ/cadastro-de-contratos#20]
We should not need to scroll the table horizontally, because it awful to use it.

**Comment by nighto** [comment]
![image](https://user-images.githubusercontent.com/397851/27102415-8dd2991c-505b-11e7-9bab-2e54bf15b0d9.png)

I don't think this is even possible at all, on my 1920x1200 screen there's horizontal scrollbar on MPRJ Transparência website.

**Comment by nighto** [comment]
What we could do eventually is to hide some columns and show a more streamlined experience on the table, showing additional data in a details page for each contract. But I think that would be a improvement for another time.

**Comment by barbier** [comment]
Omit some columns, add a link "Show more" and show the data as a list

**Comment by rlage** [comment]
Added to a backlog milestone, so we keep it in mind for later.

**Comment by nighto** [comment]
We should change `container` to `container-fluid`.

**Comment by lucianobarauna** [comment]
done !
