### ISSUE TITLE
 Confirmation screen adjustment

### ISSUE THREAD

**Issue by lucianobarauna** [MinisterioPublicoRJ/cadastro-de-contratos#22]
- Remove bartop
- Remove the green message
- Improve layout

![image](https://user-images.githubusercontent.com/1054454/27094008-18ef9882-503f-11e7-8756-f2578c5cefab.png)

**Comment by barbier** [comment]
I don't think the bar is a problem here....
Two links to help the user to log in aren't bad

**Comment by lucianobarauna** [comment]
Ok, let's at least remove a green message
